PLAT-520 Cleanup env vars
jembi/disi-on-platform pull request #18
Opened 2022-10-03 08:42 UTC by nour-borgi

2022-10-03 10:39 UTC, Mark-Labuschagne approved these changes

2022-10-04 14:24 UTC, michaelloosen requested changes

2022-10-04 14:24 UTC, michaelloosen commented on .env.local
>  STATEFUL_NODES=single
This can be removed now

2022-10-04 14:37 UTC, Mark-Labuschagne approved these changes

2022-10-04 15:56 UTC, merged