PLAT-671 Kafka Update
jembi/disi-on-platform pull request #25
Opened 2023-02-16 10:51 UTC by Mark-Labuschagne

Before this PR can be merged, we must:

- [ ] Merge https://github.com/jembi/platform/pull/219

2023-03-10 11:13 UTC, bradsawadye submitted a review, later dismissed

2023-03-27 09:59 UTC, michaelloosen requested changes

2023-03-27 11:43 UTC, nour-borgi commented on docker-compose.yml
> -    image: jembi/disi-hiv-poc-logstash:${DISI_LOGSTASH_VERSION}
yes correct, done

2023-03-27 11:45 UTC, nour-borgi commented on packages/reprocess-mediator/config/config.mjs
> +export const KAFKA_URL = process.env.KAFKA_URL || 'kafka-01:9092'
in the docker compose I keep it as it is KAFKA_URL
![image](https://user-images.githubusercontent.com/48720958/227932218-bddf5630-53ec-4c3c-8ae3-ffb4832bd40f.png)

2023-03-27 13:19 UTC, bradsawadye approved these changes

2023-03-27 13:32 UTC, merged