Plat 212 support package level stacks
jembi/disi-on-platform pull request #26
Opened 2023-03-31 09:11 UTC by arran-standish

For story https://jembiprojects.jira.com/browse/PLAT-212

2023-04-05 10:02 UTC, bradsawadye commented on docker-compose.yml
> +    external: true
```suggestion
    external: true

```

add new line at end of file

2023-04-05 10:03 UTC, bradsawadye commented on importer/analytics-datastore-elastic-search/docker-compose.config.yml
> +    external: true
above comment applies

2023-04-05 10:07 UTC, bradsawadye commented on importer/dashboard-visualiser-kibana/docker-compose.config.yml
> +    external: true
above comment applies

2023-04-05 10:08 UTC, bradsawadye commented on importer/hapi-fhir/docker-compose.config.yml
> +    external: true
above comment applies

2023-04-05 10:08 UTC, bradsawadye commented on importer/importer.sh
> +}
above comment applies

2023-04-05 10:08 UTC, bradsawadye commented on importer/openhim-core/docker-compose.config.yml
> +    external: true
above comment applies

2023-04-05 10:08 UTC, bradsawadye commented on importer/santedb-mpi/docker-compose.config.yml
> +    external: true
above comment applies

2023-04-05 10:09 UTC, bradsawadye requested changes
Looks good, just some minor things to address

2023-04-10 12:28 UTC, nour-borgi commented on package-metadata.json
> +    "FHIR_CONFIG_IMPORTER_FOLDER_NAME": "hapi-fhir",
This var is not used if I m not mistaken ?

2023-04-10 12:30 UTC, nour-borgi approved these changes
LGTM, one minor comment

2023-04-14 09:25 UTC, bradsawadye approved these changes

2023-04-14 09:25 UTC, merged